

services:
  backend:
    build: .
    env_file:
      - .env  
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - smtp4dev
    environment:
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False

  smtp4dev:
    image: rnwood/smtp4dev:latest
    container_name: smtp4dev
    restart: unless-stopped
    ports:
      - "3000:80"      # Web UI
      - "25:25"        # SMTP Server
    volumes:
      - smtp4dev-data:/app/data   # ذخیره ایمیل‌ها

volumes:
  smtp4dev-data:
# version: "3.9"  

# services:
#   web:
#     build: .
#     container_name: django_web
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./core:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     container_name: django_db
#     environment:
#       MYSQL_DATABASE: django_db
#       MYSQL_USER: django
#       MYSQL_PASSWORD: django
#       MYSQL_ROOT_PASSWORD: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
