# Generated by Django 5.2.7 on 2026-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_published_date_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(),
        ),
    ]
